# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './templates/home_map_template.ui'
#
# Created: Sun Jul 17 16:46:45 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1138, 835)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color:transparent")
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber = QtGui.QLCDNumber(Form)
        self.lcdNumber.setStyleSheet("border-width:thin;\n"
"border-color:grey;\n"
"border-style:dotted;")
        self.lcdNumber.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber.setFrameShadow(QtGui.QFrame.Raised)
        self.lcdNumber.setLineWidth(0)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 2, 9, 1, 1)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 4, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(Form)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 5, 1, 1)
        self.frame_5 = QtGui.QFrame(Form)
        self.frame_5.setStyleSheet("None")
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_6 = QtGui.QPushButton(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setMouseTracking(False)
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_6.setToolTip("None")
        self.pushButton_6.setStatusTip("None")
        self.pushButton_6.setWhatsThis("None")
        self.pushButton_6.setAccessibleName("None")
        self.pushButton_6.setAccessibleDescription("None")
        self.pushButton_6.setText("None")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ui/images/but_up_domotica.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(100, 70))
        self.pushButton_6.setShortcut("None")
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_5, 1, 9, 1, 1)
        self.frame_6 = QtGui.QFrame(Form)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_7 = QtGui.QPushButton(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ui/images/but_down_domotica.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(100, 70))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.gridLayout.addWidget(self.frame_6, 3, 9, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(Form)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 5, 4, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(Form)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 5, 5, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(Form)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 5, 6, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(Form)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 5, 7, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(Form)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 5, 8, 1, 1)
        self.time_lcd = QtGui.QLCDNumber(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_lcd.sizePolicy().hasHeightForWidth())
        self.time_lcd.setSizePolicy(sizePolicy)
        self.time_lcd.setFrameShape(QtGui.QFrame.StyledPanel)
        self.time_lcd.setFrameShadow(QtGui.QFrame.Raised)
        self.time_lcd.setLineWidth(1)
        self.time_lcd.setMidLineWidth(1)
        self.time_lcd.setNumDigits(10)
        self.time_lcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.time_lcd.setObjectName("time_lcd")
        self.gridLayout.addWidget(self.time_lcd, 5, 9, 1, 1)
        self.graphicsView = QtGui.QGraphicsView(Form)
        self.graphicsView.setMinimumSize(QtCore.QSize(800, 600))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 4, 4, 5)
        self.label_2 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 1, 1, 1)
        self.map_zoom = QtGui.QSlider(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_zoom.sizePolicy().hasHeightForWidth())
        self.map_zoom.setSizePolicy(sizePolicy)
        self.map_zoom.setMinimum(50)
        self.map_zoom.setMaximum(150)
        self.map_zoom.setProperty("value", 100)
        self.map_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.map_zoom.setInvertedAppearance(False)
        self.map_zoom.setInvertedControls(False)
        self.map_zoom.setObjectName("map_zoom")
        self.gridLayout.addWidget(self.map_zoom, 5, 2, 1, 1)
        self.level_combo = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_combo.sizePolicy().hasHeightForWidth())
        self.level_combo.setSizePolicy(sizePolicy)
        self.level_combo.setObjectName("level_combo")
        self.gridLayout.addWidget(self.level_combo, 0, 2, 1, 2)
        self.label = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.zoom_lab = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_lab.sizePolicy().hasHeightForWidth())
        self.zoom_lab.setSizePolicy(sizePolicy)
        self.zoom_lab.setObjectName("zoom_lab")
        self.gridLayout.addWidget(self.zoom_lab, 5, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setStyleSheet(QtGui.QApplication.translate("Form", "font: 75 9pt \"Sans Serif\";\n"
"background-color:transparent;\n"
"color: rgb(0, 0, 255);", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "Luces", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setStyleSheet(QtGui.QApplication.translate("Form", "font: 75 9pt \"Sans Serif\";\n"
"background-color:transparent;\n"
"color: rgb(0, 0, 255);", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Form", "Temperatura", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setStyleSheet(QtGui.QApplication.translate("Form", "background-color: transparent;", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setStyleSheet(QtGui.QApplication.translate("Form", "background-color:transparent;", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("Form", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.time_lcd.setStyleSheet(QtGui.QApplication.translate("Form", "border-width:thin;\n"
"color: rgb(0, 0, 0);\n"
"border-color:grey;\n"
"border-style:dotted", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Nivel", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_lab.setText(QtGui.QApplication.translate("Form", "100%", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
