# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './templates/manage_cards_template.ui'
#
# Created: Sun Jul 17 16:46:47 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(645, 677)
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(25, 40, 25, 25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.cards_table = QtGui.QTableWidget(Form)
        self.cards_table.setEnabled(True)
        self.cards_table.setMinimumSize(QtCore.QSize(400, 0))
        self.cards_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cards_table.setMidLineWidth(0)
        self.cards_table.setAlternatingRowColors(True)
        self.cards_table.setColumnCount(4)
        self.cards_table.setObjectName("cards_table")
        self.cards_table.setColumnCount(4)
        self.cards_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.cards_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.cards_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.cards_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.cards_table.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.cards_table, 8, 0, 1, 5)
        self.card_type_cmb = QtGui.QComboBox(Form)
        self.card_type_cmb.setMaximumSize(QtCore.QSize(100, 16777215))
        self.card_type_cmb.setObjectName("card_type_cmb")
        self.card_type_cmb.addItem("")
        self.card_type_cmb.addItem("")
        self.card_type_cmb.addItem("")
        self.gridLayout.addWidget(self.card_type_cmb, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 7)
        self.add_card_but = QtGui.QPushButton(Form)
        self.add_card_but.setMaximumSize(QtCore.QSize(100, 16777215))
        self.add_card_but.setAutoDefault(False)
        self.add_card_but.setDefault(False)
        self.add_card_but.setFlat(False)
        self.add_card_but.setObjectName("add_card_but")
        self.gridLayout.addWidget(self.add_card_but, 6, 1, 1, 1)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 7)
        self.channel_edit_error = QtGui.QLabel(Form)
        self.channel_edit_error.setEnabled(True)
        self.channel_edit_error.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 10pt \"Sans Serif\";\n"
"")
        self.channel_edit_error.setFrameShadow(QtGui.QFrame.Plain)
        self.channel_edit_error.setObjectName("channel_edit_error")
        self.gridLayout.addWidget(self.channel_edit_error, 5, 2, 1, 1)
        self.channel_edit = QtGui.QLineEdit(Form)
        self.channel_edit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.channel_edit.setObjectName("channel_edit")
        self.gridLayout.addWidget(self.channel_edit, 5, 1, 1, 1)
        self.addr_edit_error = QtGui.QLabel(Form)
        self.addr_edit_error.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.addr_edit_error.setFont(font)
        self.addr_edit_error.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 10pt \"Sans Serif\";\n"
"")
        self.addr_edit_error.setObjectName("addr_edit_error")
        self.gridLayout.addWidget(self.addr_edit_error, 4, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(64, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 4)
        self.error_msg = QtGui.QLabel(Form)
        self.error_msg.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 10pt \"Sans Serif\";")
        self.error_msg.setObjectName("error_msg")
        self.gridLayout.addWidget(self.error_msg, 4, 3, 2, 4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 14, 0, 1, 5)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 14, 5, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 8, 6, 1, 1)
        self.addr_edit = QtGui.QLineEdit(Form)
        self.addr_edit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.addr_edit.setObjectName("addr_edit")
        self.gridLayout.addWidget(self.addr_edit, 4, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem5, 2, 0, 1, 7)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 10, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 9, 0, 1, 1)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 12, 0, 1, 1)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 11, 0, 1, 7)
        self.channel_cmb = QtGui.QComboBox(Form)
        self.channel_cmb.setObjectName("channel_cmb")
        self.channel_cmb.addItem("")
        self.channel_cmb.addItem("")
        self.channel_cmb.addItem("")
        self.channel_cmb.addItem("")
        self.channel_cmb.addItem("")
        self.channel_cmb.addItem("")
        self.channel_cmb.addItem("")
        self.channel_cmb.addItem("")
        self.channel_cmb.addItem("")
        self.channel_cmb.addItem("")
        self.gridLayout.addWidget(self.channel_cmb, 12, 1, 1, 1)
        self.search_cards_but = QtGui.QPushButton(Form)
        self.search_cards_but.setObjectName("search_cards_but")
        self.gridLayout.addWidget(self.search_cards_but, 12, 4, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 12, 2, 1, 1)
        self.scrollArea = QtGui.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 408, 57))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.channel_msg = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.channel_msg.setText("")
        self.channel_msg.setObjectName("channel_msg")
        self.horizontalLayout_2.addWidget(self.channel_msg)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 13, 0, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.addr_edit, QtCore.SIGNAL("textEdited(QString)"), self.addr_edit_error.hide)
        QtCore.QObject.connect(self.add_card_but, QtCore.SIGNAL("clicked()"), Form.add_card)
        QtCore.QObject.connect(self.channel_edit, QtCore.SIGNAL("textEdited(QString)"), self.channel_edit_error.hide)
        QtCore.QObject.connect(self.addr_edit, QtCore.SIGNAL("textEdited(QString)"), self.error_msg.hide)
        QtCore.QObject.connect(self.channel_edit, QtCore.SIGNAL("textEdited(QString)"), self.error_msg.hide)
        QtCore.QObject.connect(self.channel_edit, QtCore.SIGNAL("returnPressed()"), Form.add_card)
        QtCore.QObject.connect(self.search_cards_but, QtCore.SIGNAL("pressed()"), Form.search_connected_cards)
        QtCore.QObject.connect(self.addr_edit, QtCore.SIGNAL("returnPressed()"), Form.add_card)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.card_type_cmb, self.addr_edit)
        Form.setTabOrder(self.addr_edit, self.channel_edit)
        Form.setTabOrder(self.channel_edit, self.add_card_but)
        Form.setTabOrder(self.add_card_but, self.cards_table)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.cards_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Form", "Id", None, QtGui.QApplication.UnicodeUTF8))
        self.cards_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Form", "Serial", None, QtGui.QApplication.UnicodeUTF8))
        self.cards_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Form", "Tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.cards_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Form", "Borrar", None, QtGui.QApplication.UnicodeUTF8))
        self.card_type_cmb.setItemText(0, QtGui.QApplication.translate("Form", "Digital", None, QtGui.QApplication.UnicodeUTF8))
        self.card_type_cmb.setItemText(1, QtGui.QApplication.translate("Form", "Analogica", None, QtGui.QApplication.UnicodeUTF8))
        self.card_type_cmb.setItemText(2, QtGui.QApplication.translate("Form", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Tipo", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Agregar Placa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Direccion", None, QtGui.QApplication.UnicodeUTF8))
        self.add_card_but.setText(QtGui.QApplication.translate("Form", "Agregar Placa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Serial", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_edit_error.setText(QtGui.QApplication.translate("Form", "Ingrese un valor entre 0 y 9", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_edit.setToolTip(QtGui.QApplication.translate("Form", "Numero de puerto serial de 0 a 9", None, QtGui.QApplication.UnicodeUTF8))
        self.addr_edit_error.setText(QtGui.QApplication.translate("Form", "Ingrese un numero par >= 0 y < 80", None, QtGui.QApplication.UnicodeUTF8))
        self.error_msg.setText(QtGui.QApplication.translate("Form", "Error", None, QtGui.QApplication.UnicodeUTF8))
        self.addr_edit.setToolTip(QtGui.QApplication.translate("Form", "Direccion en decimal de la placa", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Testear Canal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Canal", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_cmb.setItemText(0, QtGui.QApplication.translate("Form", "Canal 0", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_cmb.setItemText(1, QtGui.QApplication.translate("Form", "Canal 1 ", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_cmb.setItemText(2, QtGui.QApplication.translate("Form", "Canal 2", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_cmb.setItemText(3, QtGui.QApplication.translate("Form", "Canal 3", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_cmb.setItemText(4, QtGui.QApplication.translate("Form", "Canal 4", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_cmb.setItemText(5, QtGui.QApplication.translate("Form", "Canal 5", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_cmb.setItemText(6, QtGui.QApplication.translate("Form", "Canal 6", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_cmb.setItemText(7, QtGui.QApplication.translate("Form", "Canal 7", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_cmb.setItemText(8, QtGui.QApplication.translate("Form", "Canal 8 ", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_cmb.setItemText(9, QtGui.QApplication.translate("Form", "Canal 9", None, QtGui.QApplication.UnicodeUTF8))
        self.search_cards_but.setText(QtGui.QApplication.translate("Form", "Buscar placas", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
